board_node: "192.168.1.80:5554"
pilot_config: "/home/neobotix/ros_workspace/src/neo_relayboard_v3/config/default/rox-argo"
agm_batteries_config: "/home/neobotix/ros_workspace/src/neo_relayboard_v3/config/addons/agm-batteries"
lfp_batteries: false # Set to True if you have LFP Batteries
lfp_batteries_config: "/home/neobotix/ros_workspace/src/neo_relayboard_v3/config/addons/lfp-batteries"
use_multipowr: false #Set to True if you have wallbox
multipowr_config: "/home/neobotix/ros_workspace/src/neo_relayboard_v3/config/addons/smart-charger" 